#! /usr/bin/env python

import fileinput
import json
import sys

# load the file

# For each tuple..
for line in fileinput.input():
  '''
  From: mention theta join entity
  To: candidate_link(id, eid, mid, is_correct)
  '''
  
  mid = row["mention.id"]
  eid = row["entity.id"]

  # Dummy extractor that basically just outputs the line (all the work is done by our query)
  if mid is not None and eid is not None:
    # must specify everything except for id, which will be automatically generated by psql
    print json.dumps({"eid": eid, "mid": int(mid), "is_correct": None})
